"use client";

export default function CommentaryCard({ commentary = "", loading = false }) {
  return (
    <div className="space-y-2">
      <h3 className="font-semibold text-sm">AI Market Insight</h3>

      {loading ? (
        <div className="chat chat-start">
          <div className="chat-image avatar">
            <div className="w-8 rounded-full bg-base-300 flex items-center justify-center">
              <span className="text-sm">🤖</span>
            </div>
          </div>
          <div className="chat-bubble chat-bubble-base-300">
            <div className="space-y-1">
              <div className="skeleton h-3 w-40" />
              <div className="skeleton h-3 w-32" />
              <div className="skeleton h-3 w-36" />
            </div>
          </div>
        </div>
      ) : commentary ? (
        <div className="chat chat-start">
          <div className="chat-image avatar">
            <div className="w-8 rounded-full bg-primary/20 flex items-center justify-center">
              <span className="text-sm">🤖</span>
            </div>
          </div>
          <div className="chat-header text-xs opacity-50 mb-1">
            Noble Trader AI
          </div>
          <div className="chat-bubble chat-bubble-primary text-wrap max-w-none">
            {commentary}
          </div>
          <div className="chat-footer opacity-50 text-xs mt-1">
            Generated by AI · Not financial advice
          </div>
        </div>
      ) : (
        <div className="chat chat-start">
          <div className="chat-image avatar">
            <div className="w-8 rounded-full bg-base-300 flex items-center justify-center">
              <span className="text-sm">🤖</span>
            </div>
          </div>
          <div className="chat-bubble chat-bubble-base-300 opacity-50">
            Run an analysis to generate AI commentary.
          </div>
        </div>
      )}
    </div>
  );
}
