"use client";

export default function CommentaryCard({ commentary = "", loading = false }) {
  return (
    <div className="card bg-base-100 shadow-xl">
      <div className="card-body">
        <h2 className="card-title">🤖 AI Market Insight</h2>

        {loading ? (
          <div className="chat chat-start mt-2">
            <div className="chat-image avatar">
              <div className="w-10 rounded-full bg-base-300 flex items-center justify-center">
                <span className="text-lg">🤖</span>
              </div>
            </div>
            <div className="chat-bubble chat-bubble-base-300">
              <div className="space-y-2">
                <div className="skeleton h-3 w-40" />
                <div className="skeleton h-3 w-32" />
                <div className="skeleton h-3 w-36" />
              </div>
            </div>
          </div>
        ) : commentary ? (
          <div className="chat chat-start mt-2">
            <div className="chat-image avatar">
              <div className="w-10 rounded-full bg-primary/20 flex items-center justify-center">
                <span className="text-lg">🤖</span>
              </div>
            </div>
            <div className="chat-header text-xs opacity-50 mb-1">
              Noble Trader AI
            </div>
            <div className="chat-bubble chat-bubble-primary text-wrap">
              {commentary}
            </div>
            <div className="chat-footer opacity-50 text-xs mt-1">
              Generated by AI · Not financial advice
            </div>
          </div>
        ) : (
          <div className="chat chat-start mt-2">
            <div className="chat-image avatar">
              <div className="w-10 rounded-full bg-base-300 flex items-center justify-center">
                <span className="text-lg">🤖</span>
              </div>
            </div>
            <div className="chat-bubble chat-bubble-base-300 opacity-50">
              Run an analysis to generate AI commentary.
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
